import Head from 'next/head'
import Header from './components/Header/Header'
import Content from './components/Content'
import { useState, useEffect } from 'react'
import { useRouter } from 'next/router'
import { $fetch } from 'ofetch'
import { SteamUserInfo } from '../types'

export default function Home() {
  const router = useRouter()
  const openid = router.query.openid
  const [userInfo, setUserInfo] = useState<null | SteamUserInfo>(null)

  async function getSteamUserInfo() {
    const steamUserInfo = window.localStorage.getItem('steam-user-info')

    if (openid && !steamUserInfo) {
      const response = await $fetch('/api/info/steam', {
        params: {
          openid,
        },
      })

      if (response.state === 'ok') {
      }
      window.localStorage.setItem('steam-user-info', JSON.stringify(response))
    } else if (steamUserInfo) {
      setUserInfo(JSON.parse(steamUserInfo))
    }
  }

  useEffect(() => {
    getSteamUserInfo()
  }, [openid])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header userInfo={userInfo} />
        <Content userInfo={userInfo} />
      </main>
    </>
  )
}
